"""Structured audit event type constants."""

LOGIN_SUCCESS = "LOGIN_SUCCESS"
LOGIN_FAILURE = "LOGIN_FAILURE"
LOGIN_PASSWORD_VERIFIED = "LOGIN_PASSWORD_VERIFIED"
ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
LOGOUT = "LOGOUT"
SESSION_LOCKED = "SESSION_LOCKED"
SESSION_UNLOCKED = "SESSION_UNLOCKED"
SESSION_EXPIRED = "SESSION_EXPIRED"
PASSWORD_CHANGED = "PASSWORD_CHANGED"
MFA_ENABLED = "MFA_ENABLED"
MFA_DISABLED = "MFA_DISABLED"
MFA_CHALLENGE_SUCCESS = "MFA_CHALLENGE_SUCCESS"
MFA_CHALLENGE_FAILED = "MFA_CHALLENGE_FAILED"
FILE_ENCRYPTED = "FILE_ENCRYPTED"
FILE_DECRYPTED = "FILE_DECRYPTED"
DECRYPTION_FAILED = "DECRYPTION_FAILED"
INTEGRITY_FAILURE = "INTEGRITY_FAILURE"
FILE_SCANNED = "FILE_SCANNED"
FILE_QUARANTINED = "FILE_QUARANTINED"
FILE_RESTORED = "FILE_RESTORED"
SECURE_DELETE = "SECURE_DELETE"
SETTINGS_CHANGED = "SETTINGS_CHANGED"

ALL_EVENT_TYPES = {
    name: value
    for name, value in list(globals().items())
    if name.isupper() and isinstance(value, str)
}
